dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - langs
     - embeddings
  corpus:
    root: /u/scr/ethanchi/langs
    train_path: train.conllu
    dev_path: dev.conllu
    test_path: test.conllu 
  embeddings:
    type: token #(token,subword)
    root: /u/scr/ethanchi/hdf5
    train_path: train-multilingual.hdf5
    dev_path: dev-multilingual.hdf5
    test_path: test-multilingual.hdf5
  keys:
    train: ['es']
    dev: ['es']
    test: ['es']
  batch_size: 20
model:
  hidden_dim: 768 # ELMo hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 6 # BERT-base: (1,...,12); ELMo: (1,2,3)
  multilingual: True
probe:
  task_signature: word_pair # word, word_pair
  task_name: parse-distance
  maximum_rank: 8
  psd_parameters: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: /u/scr/ethanchi/probingOutputs 
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
      #- image_examples
    - uuas
    - proj_acc
    - adj_acc
